line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "W", "I", "N", "UP"]
ignore = ["E501", "N803", "N806", "N812", "N815", "N817"]

exclude = [
  ".git",
  "__pycache__",
  ".venv",
  "venv",
  "build",
  "dist",
]

[lint.per-file-ignores]
"tests/**" = ["E402"]
